CREATE TABLE supervisor_report (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    full_name VARCHAR(300) NOT NULL,
    date_enregistrement DATE,
    lieu_activite VARCHAR(100),
    stock_sim_activees INTEGER,
    stock_sim_blanches INTEGER,
    sim_appro INTEGER,
    gsm INTEGER,
    momo_app INTEGER,
    mymtn INTEGER,
    ayoba INTEGER,
    telephone INTEGER,
    modem INTEGER,
    mifi INTEGER,
    wifix INTEGER,
    difficulte TEXT,
    momo_convertion INTEGER,
    resetpin INTEGER,
    prospection_ca INTEGER,
    besoin TEXT,
    concurrentielle TEXT,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES auth_user(id)
);
