# Generated by Django 4.2.20 on 2025-05-11 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField()),
                ('total_accepted', models.IntegerField()),
            ],
            options={
                'db_table': 'accepted_sim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField()),
                ('total_sim', models.IntegerField()),
            ],
            options={
                'db_table': 'all_sim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoachMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mpos', models.CharField(max_length=20, unique=True)),
                ('reg_user_name', models.CharField(max_length=50)),
                ('noms_prenoms', models.CharField(max_length=100)),
                ('numero_cni', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'coach_mobile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrossAddSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField()),
                ('total_gross_add', models.IntegerField()),
            ],
            options={
                'db_table': 'gross_add_sim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectifGsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(unique=True)),
                ('objectif', models.IntegerField()),
            ],
            options={
                'db_table': 'objectif_gsm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Superviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('adresse_mail', models.EmailField(max_length=100, unique=True)),
                ('numero_telephone', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'superviseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SyntheseGsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jour', models.DateField()),
                ('total_all_sim', models.IntegerField(default=0)),
                ('total_accepted_sim', models.IntegerField(default=0)),
                ('taux_accepted', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_gross_add_sim', models.IntegerField(default=0)),
                ('taux_gross_add', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('jour_presence', models.IntegerField(default=0)),
                ('taux_presence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('drip', models.CharField(default='Accidental', max_length=20)),
                ('productivity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'synthese_gsm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='supervisor_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('lieu_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_sim_activees', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_sim_blanches', models.PositiveIntegerField(blank=True, null=True)),
                ('sim_appro', models.PositiveIntegerField(blank=True, null=True)),
                ('gsm', models.PositiveIntegerField(blank=True, null=True)),
                ('momo_app', models.PositiveIntegerField(blank=True, null=True)),
                ('mymtn', models.PositiveIntegerField(blank=True, null=True)),
                ('ayoba', models.PositiveIntegerField(blank=True, null=True)),
                ('telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('modem', models.PositiveIntegerField(blank=True, null=True)),
                ('mifi', models.PositiveIntegerField(blank=True, null=True)),
                ('wifix', models.PositiveIntegerField(blank=True, null=True)),
                ('canal_alternative', models.PositiveBigIntegerField(blank=True, null=True)),
                ('difficulte', models.TextField(blank=True, null=True)),
                ('momoconvertion', models.PositiveIntegerField(blank=True, null=True)),
                ('resetpin', models.PositiveIntegerField(blank=True, null=True)),
                ('prospection', models.TextField(blank=True, null=True)),
                ('besoin', models.TextField(blank=True, null=True)),
                ('concurrentielle', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='momo_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateField()),
                ('heure_creation', models.TimeField()),
                ('nom_merchant', models.CharField(max_length=255)),
                ('nom_etablissement', models.CharField(max_length=255)),
                ('localisation_merchant', models.CharField(max_length=255)),
                ('reference_adresse', models.TextField(blank=True, null=True)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('numero_merchant', models.CharField(max_length=50, unique=True)),
                ('identifiant_merchant', models.CharField(max_length=50, unique=True)),
                ('montant_transaction', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
