# Generated by Django 4.2.20 on 2025-05-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_acceptedsim_allsim_coachmobile_grossaddsim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor_report',
            old_name='momoconvertion',
            new_name='momo_convertion',
        ),
        migrations.RenameField(
            model_name='supervisor_report',
            old_name='prospection',
            new_name='prospection_ca',
        ),
        migrations.RemoveField(
            model_name='supervisor_report',
            name='canal_alternative',
        ),
        migrations.DeleteModel(
            name='momo_pay',
        ),
    ]
