# Generated by Django 4.2.20 on 2025-05-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_rename_momoconvertion_supervisor_report_momo_convertion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor_report',
            options={'managed': False},
        ),
    ]
